// Default categories with their match keywords — the canonical list used by
// the seeder (src/db/seed.ts) and the suggestion tests. Migration
// 0015_category_keywords.sql mirrors this data for existing databases; keep
// the two in sync when editing.
//
// Keywords drive category suggestion (src/lib/category-suggest.ts): they are
// matched against a model's title, tags and — for imports — the source
// platform's own category names. The lists therefore include the MakerWorld
// taxonomy (and Printables' near-identical one) mapped onto our smaller set:
// e.g. MakerWorld's "Signs & Logos"/"Sculptures" → Art, "3D printer parts" →
// Functional, "Props & Cosplay" → Fashion. We deliberately do NOT create new
// categories from source data — source categories only rank the existing
// ones, so imports can't sprawl the taxonomy. "Other" has no keywords: it is
// the fallback when nothing matches, never a positive suggestion.
export type DefaultCategory = {
  name: string;
  slug: string;
  keywords: string[];
};

export const DEFAULT_CATEGORIES: DefaultCategory[] = [
  {
    name: "Art",
    slug: "art",
    keywords: [
      "art",
      "2d art",
      "coin",
      "badge",
      "coin & badges",
      "sign",
      "logo",
      "signs & logos",
      "sculpture",
      "statue",
      "bust",
      "relief",
      "lithophane",
      "wall art",
      "painting",
      "drawing",
    ],
  },
  {
    name: "Fashion",
    slug: "fashion",
    keywords: [
      "fashion",
      "bag",
      "clothes",
      "clothing",
      "earring",
      "footwear",
      "shoe",
      "glasses",
      "sunglasses",
      "jewelry",
      "jewellery",
      "jewlery", // MakerWorld's spelling of its Jewlery subcategory
      "ring",
      "bracelet",
      "necklace",
      "pendant",
      "keychain",
      "wearable",
      "cosplay",
      "props & cosplay",
      "costume",
      "mask",
      "helmet",
      "masks & helmets",
    ],
  },
  {
    name: "Functional",
    slug: "functional",
    keywords: [
      "functional",
      "3d printer",
      "3d printer accessories",
      "3d printer parts",
      "test models",
      "calibration",
      "benchy",
      "spool",
      "filament",
      "ams",
      "mount",
      "bracket",
      "holder",
      "hook",
      "clip",
      "clamp",
      "stand",
      "hinge",
      "adapter",
      "spacer",
      "repair",
      "replacement",
      "spare part",
    ],
  },
  {
    name: "Gadgets",
    slug: "gadgets",
    keywords: [
      "gadget",
      "hobby & diy",
      "electronics",
      "electronic",
      "rc",
      "robotics",
      "robot",
      "drone",
      "fpv",
      "arduino",
      "raspberry pi",
      "esp32",
      "music",
      "headphone",
      "speaker",
      "camera",
      "phone",
      "smartphone",
      "tablet",
      "laptop",
      "keyboard",
      "controller",
      "vehicle",
      "sport & outdoors",
    ],
  },
  {
    name: "Games & Toys",
    slug: "games-toys",
    keywords: [
      "toy",
      "toys & games",
      "game",
      "board game",
      "puzzle",
      "jigsaw",
      "dice",
      "chess",
      "fidget",
      "spinner",
      "character",
      "outdoor toys",
      "construction sets",
      "brick",
      "card game",
    ],
  },
  {
    name: "Household",
    slug: "household",
    keywords: [
      "household",
      "home",
      "decor",
      "decoration",
      "decorative",
      "festivities",
      "holiday",
      "christmas",
      "halloween",
      "easter",
      "garden",
      "planter",
      "plant",
      "vase",
      "pot",
      "office",
      "desk",
      "pet",
      "dog",
      "cat",
      "kitchen",
      "bathroom",
      "furniture",
      "lamp",
      "lighting",
      "shelf",
      "coaster",
    ],
  },
  {
    name: "Miniatures",
    slug: "miniatures",
    keywords: [
      "miniature",
      "mini",
      "animal",
      "architecture",
      "building",
      "creature",
      "dragon",
      "people",
      "figure",
      "figurine",
      "terrain",
      "tabletop",
      "dnd",
      "d&d",
      "warhammer",
      "scale model",
      "diorama",
    ],
  },
  {
    name: "Tools",
    slug: "tools",
    keywords: [
      "tool",
      "hand tools",
      "machine tools",
      "measure tools",
      "measuring",
      "medical tools",
      "organizer",
      "gridfinity",
      "jig",
      "wrench",
      "screwdriver",
      "drill",
      "saw",
      "ruler",
      "caliper",
      "workshop",
      "workbench",
      "garage",
      "storage",
      "box",
      "container",
      "tray",
      "sorter",
    ],
  },
  // The fallback — deliberately no keywords, so it never wins a suggestion
  // but every model without a match lands here instead of staying blank.
  { name: "Other", slug: "other", keywords: [] },
];

export const OTHER_CATEGORY_SLUG = "other";
