import { test } from "node:test";
import assert from "node:assert/strict";
import { strFromU8, strToU8, unzipSync, zipSync } from "fflate";
import { applyPrinterOverride } from "@/lib/threemf-printer";
import { readSliceData, type RangeReader } from "@/lib/threemf-slice-info";

// Serves an in-memory archive the way S3 serves ranged GETs (inclusive end,
// clamped to the object size) — same helper as threemf-slice-info.test.ts.
function readerFor(bytes: Uint8Array): { readRange: RangeReader; size: number } {
  return {
    size: bytes.length,
    readRange: async (start, end) =>
      bytes.subarray(start, Math.min(end + 1, bytes.length)),
  };
}

const MODEL_XML = `<model unit="millimeter"><resources/></model>`;

test("applyPrinterOverride rewrites the Bambu printer identity, nothing else", () => {
  const zip = zipSync({
    "3D/3dmodel.model": strToU8(MODEL_XML),
    "Metadata/project_settings.config": strToU8(
      JSON.stringify({
        printer_model: "Bambu Lab X1 Carbon",
        printer_settings_id: "Bambu Lab X1 Carbon 0.4 nozzle",
        // Two extruder slots (H2D-style) — the count must survive the patch.
        nozzle_diameter: ["0.4", "0.4"],
        printable_area: ["0x0", "256x0", "256x256", "0x256"],
        // A process setting the override must not touch.
        layer_height: "0.2",
      }),
    ),
  });

  const patched = applyPrinterOverride(zip, {
    model: "Bambu Lab H2D",
    nozzleDiameterMm: 0.6,
    bedSizeMm: { x: 350, y: 320 },
  });
  assert.ok(patched);
  const entries = unzipSync(patched);
  const settings = JSON.parse(
    strFromU8(entries["Metadata/project_settings.config"]),
  );
  assert.equal(settings.printer_model, "Bambu Lab H2D");
  // The settings id follows Bambu's system preset naming so the desktop
  // slicer selects the machine when the download is opened as a project.
  assert.equal(settings.printer_settings_id, "Bambu Lab H2D 0.6 nozzle");
  assert.deepEqual(settings.nozzle_diameter, ["0.6", "0.6"]);
  assert.deepEqual(settings.printable_area, ["0x0", "350x0", "350x320", "0x320"]);
  assert.equal(settings.layer_height, "0.2");
  // The geometry entry is carried over untouched.
  assert.equal(strFromU8(entries["3D/3dmodel.model"]), MODEL_XML);
});

test("a patched archive reads back as the overridden PrinterInfo", async () => {
  // The write path must feed the read path: what applyPrinterOverride stores
  // is exactly what readSliceData derives on the next slice pass.
  const zip = zipSync({
    "Metadata/project_settings.config": strToU8(
      JSON.stringify({
        printer_model: "Bambu Lab X1 Carbon",
        nozzle_diameter: ["0.4"],
        printable_area: ["0x0", "256x0", "256x256", "0x256"],
      }),
    ),
  });
  const patched = applyPrinterOverride(zip, {
    model: "Bambu Lab A1 mini",
    nozzleDiameterMm: 0.2,
    bedSizeMm: { x: 180, y: 180 },
  });
  assert.ok(patched);
  const { readRange, size } = readerFor(patched);
  const data = await readSliceData(readRange, size);
  assert.equal(data?.printerInfo?.model, "Bambu Lab A1 mini");
  assert.equal(data?.printerInfo?.nozzleDiameterMm, 0.2);
  assert.deepEqual(data?.printerInfo?.bedSizeMm, { x: 180, y: 180 });
});

test("applyPrinterOverride patches a PrusaSlicer ini in place", () => {
  const zip = zipSync({
    "Metadata/Slic3r_PE.config": strToU8(
      [
        "; generated by PrusaSlicer",
        "bed_shape = 0x0,250x0,250x210,0x210",
        "nozzle_diameter = 0.4,0.4",
        "fill_density = 15%",
      ].join("\n"),
    ),
  });
  const patched = applyPrinterOverride(zip, {
    model: "Bambu Lab P1S",
    nozzleDiameterMm: 0.6,
    bedSizeMm: { x: 256, y: 256 },
  });
  assert.ok(patched);
  const ini = strFromU8(unzipSync(patched)["Metadata/Slic3r_PE.config"]);
  assert.match(ini, /^bed_shape = 0x0,256x0,256x256,0x256$/m);
  // Per-extruder list keeps its slot count.
  assert.match(ini, /^nozzle_diameter = 0\.6,0\.6$/m);
  // printer_model wasn't in the file — appended, so the reader finds it.
  assert.match(ini, /^printer_model = Bambu Lab P1S$/m);
  assert.match(ini, /^fill_density = 15%$/m);
});

test("an archive without slicer settings gets a minimal Bambu config", async () => {
  // Plain core-spec 3mf (e.g. an Onshape export): the created entry is enough
  // for the slicer service's whitelist translation (nozzle_diameter) and for
  // readSliceData to re-derive the same profile.
  const zip = zipSync({ "3D/3dmodel.model": strToU8(MODEL_XML) });
  const patched = applyPrinterOverride(zip, {
    model: "Bambu Lab P1S",
    nozzleDiameterMm: 0.4,
    bedSizeMm: { x: 256, y: 256 },
  });
  assert.ok(patched);
  const entries = unzipSync(patched);
  assert.equal(strFromU8(entries["3D/3dmodel.model"]), MODEL_XML);
  const { readRange, size } = readerFor(patched);
  const data = await readSliceData(readRange, size);
  assert.equal(data?.printerInfo?.model, "Bambu Lab P1S");
  assert.deepEqual(data?.printerInfo?.bedSizeMm, { x: 256, y: 256 });
});

test("stripPredictions drops inherited estimates but keeps the plate list", async () => {
  // A printer derivative is a byte-copy of its source, so it would inherit
  // the predictions sliced for the ORIGINAL machine. Creating a derivative
  // strips them (forcing a fresh slicer estimate for the new printer), while
  // plate blocks stay so plate counts survive. A plain override keeps the
  // file's own predictions untouched.
  const sliceInfo = `<config>
  <plate>
    <metadata key="index" value="1"/>
    <metadata key="prediction" value="3600"/>
    <metadata key="weight" value="12.5"/>
  </plate>
  <plate>
    <metadata key="prediction" value="1800"/>
    <metadata key="weight" value="7.5"/>
  </plate>
</config>`;
  const zip = zipSync({
    "Metadata/slice_info.config": strToU8(sliceInfo),
    "Metadata/project_settings.config": strToU8(
      JSON.stringify({ printer_model: "Bambu Lab X1 Carbon" }),
    ),
  });
  const override = { model: "Bambu Lab P2S", nozzleDiameterMm: 0.8 };

  const derivative = applyPrinterOverride(zip, override, {
    stripPredictions: true,
  });
  assert.ok(derivative);
  const stripped = readerFor(derivative);
  const strippedData = await readSliceData(stripped.readRange, stripped.size);
  assert.equal(strippedData?.sliceInfo?.printTimeSeconds, null);
  assert.equal(strippedData?.sliceInfo?.filamentGrams, null);
  assert.equal(strippedData?.sliceInfo?.plateCount, 2);

  const inPlace = applyPrinterOverride(zip, override);
  assert.ok(inPlace);
  const kept = readerFor(inPlace);
  const keptData = await readSliceData(kept.readRange, kept.size);
  assert.equal(keptData?.sliceInfo?.printTimeSeconds, 5400);
});

test("applyPrinterOverride leaves archives it can't understand alone", () => {
  // Not a ZIP at all → null (caller stores the override in the DB only).
  assert.equal(
    applyPrinterOverride(strToU8("not a zip"), { model: "Bambu Lab P1S" }),
    null,
  );
  // project_settings.config exists but isn't the expected JSON — don't
  // clobber content we don't understand.
  const weird = zipSync({
    "Metadata/project_settings.config": strToU8("<not-json/>"),
  });
  assert.equal(applyPrinterOverride(weird, { model: "Bambu Lab P1S" }), null);
});
